[tox]
envlist = py310-sql, py310-nosql
skipsdist = True

[testenv]
deps =
    -r requirements.txt
    pytest-cov
setenv =
    PYTHONPATH = {toxinidir}/main/python

commands =
    pytest --cov=main --cov-report=term-missing {posargs:tests/python}

[testenv:py310-sql]
setenv =
    PYTHONPATH = {toxinidir}/main/python
    DB_ENGINE = SQL
    DATABASE_URL = sqlite+aiosqlite:///{toxinidir}/test.db
commands =
    pytest --cov=main --cov-report=term-missing tests/python/sql  -q 
    pytest --cov=main --cov-report=term-missing tests/python/api  -q 
    pytest --cov=main --cov-report=term-missing tests/python/services -q 

[testenv:py310-nosql]
setenv =
    PYTHONPATH = {toxinidir}/main/python
    DB_ENGINE = NOSQL
commands =
    pytest --cov=main --cov-report=term-missing tests/python/nosql tests/python/api -q


; [testenv:lint]
; description = Run linters
; deps = flake8
; commands = # Run flake8 against the main application and test code
;     flake8 main/python tests


; [testenv:e2e]
; description = Run end-to-end tests with behave
; deps =
;     -r requirements.txt
;     -r requirements-dev.txt
; commands =
;     behave features
; setenv = {[testenv]setenv}


; [testenv:bandit]
; description = run bandit
; deps =
;     bandit
; commands =
;     bandit -rv main/python