[tox]
envlist = py310-serverless
skipsdist = True

[testenv]
deps =
    -r requirements.txt
    pytest-cov
setenv =
    PYTHONPATH = {toxinidir}

[testenv:py310-serverless]
setenv =
    PYTHONPATH = {toxinidir}
    AWS_ACCESS_KEY_ID = testing
    AWS_SECRET_ACCESS_KEY = testing
    AWS_DEFAULT_REGION = us-east-1
commands =
    pytest --cov=serverless --cov-report=term-missing tests/python/serverless -q