[tox]
envlist = py310
skipsdist = True

[testenv]
deps =
    -r requirements.txt
    pytest-cov
commands =
    pytest --cov=main --cov-report=term-missing {posargs:tests}
setenv =
    PYTHONPATH = {toxinidir}/python/main
    DATABASE_URL = "sqlite:///{toxinidir}/test.db"



; [testenv:lint]
; description = Run linters
; deps = flake8
; commands = # Run flake8 against the main application and test code
;     flake8 main/python tests


; [testenv:e2e]
; description = Run end-to-end tests with behave
; deps =
;     -r requirements.txt
;     -r requirements-dev.txt
; commands =
;     behave features
; setenv = {[testenv]setenv}


; [testenv:bandit]
; description = run bandit
; deps =
;     bandit
; commands =
;     bandit -rv main/python