[tox]
envlist = py311
skipsdist = True

[testenv]
deps =
    -r requirements.txt
    pytest-cov
commands =
    pytest --cov=main --cov-report=term-missing {posargs:tests}
setenv =
    PYTHONPATH = {toxinidir}/main